hmmer:
  bin: /mnt/shared/scratch/vhoikkal/private/pipelines/ring_nucleases/crispr_type_iii_effector_finder/.snakemake/conda/6bada1b53b2b3df559eaa4f81975c2ea_/bin/hmmsearch
  e_value_threshold: 0.00445
  pvog_path: /home/vhoikkal/scratch/private/databases/pvog/allpvoghmms
phigaro:
  mean_gc: 0.46354823199323625
  penalty_black: 2.2
  penalty_white: 0.7
  threshold_max_abs: 52.96
  threshold_max_basic: 46.0
  threshold_max_without_gc: 11.42
  threshold_min_abs: 50.32
  threshold_min_basic: 45.39
  threshold_min_without_gc: 11.28
  window_len: 32
  delete_shorts: True
prodigal:
  bin: /mnt/shared/scratch/vhoikkal/private/pipelines/ring_nucleases/crispr_type_iii_effector_finder/.snakemake/conda/6bada1b53b2b3df559eaa4f81975c2ea_/bin/prodigal
